services:
  proto-builder:
    image: proto-builder
    build:
      dockerfile: proto.dockerfile

  server:
    image: mafia-server
    build:
      context: ./
      dockerfile: server.dockerfile
    environment:
      MESSENGER_SERVER_PORT: 51075
    ports:
      - 51075:51075

  client:
    image: mafia-client
    build:
      context: ./
      dockerfile: client.dockerfile
    environment:
      MESSENGER_SERVER_ADDR: server:51075
